let recipes = {
  "1": {
    "Oven":[
        {
        "name":"Plate",
        "tier":1,
        "count":4
      },
      {
        "name":"InsulCable",
        "tier":1,
        "count":2
      }],
    "InsulCable":[
        {
      "name":"Cable",
      "tier":1,
      "count":1
      },
      {
        "name":"Rubber",
        "tier":0,
        "count":1
      }],
    "Presser":[
        {
      "name":"Plate",
      "tier":1,
      "count":4
      },
      {
       "name":"Chip",
       "tier":1,
       "count":2
      },
      {
       "name":"Hammer",
       "tier":1,
       "count":2
      },
      {
       "name":"Spin",
       "tier":1,
       "count":1
      }],
    "Belt":[
        {
      "name":"Rubber",
      "tier":0,
      "count":3
    },{
      "name":"Motor",
      "tier":0,
      "count":3
    },{
      "name":"InsulCable",
      "tier":0,
      "count":3
    }],
    "Chip":[
      {
        "name":"Circuits",
        "tier":1,
        "count":2
      },
      {
        "name":"Circuits",
        "tier":2,
        "count":2
      },
      {
        "name":"RefPlate",
        "tier":1,
        "count":1
      },
      {
        "name":"RefPlate",
        "tier":2,
        "count":1
      }
    ],
    "Crusher":[
      {
        "name":"Chip",
        "tier":1,
        "count":1
      },{
        "name":"Motor",
        "tier":1,
        "count":1
      },{
        "name":"StackedPlate",
        "tier":1,
        "count":7
      }
    ],
    "StackedPlate":[
      {
        "name":"Plate",
        "tier":1,
        "count":7
      }
    ],
    "Motor":[
      {
        "name":"Plate",
        "tier":0,
        "count":4
      },
      {
        "name":"Rod",
        "tier":0,
        "count":2
      },{
        "name":"Spin",
        "tier":0,
        "count":1
      },{
        "name":"Bolt",
        "tier":0,
        "count":1
      },{
        "name":"Rubber",
        "tier":0,
        "count":1
      }],
    "Mixer":[
      {
        "name":"Plate",
        "tier":0,
        "count":5
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Pump",
        "tier":0,
        "count":1
      },{
        "name":"Chip",
        "tier":0,
        "count":1
      }
    ],
    "Pump":[
      {
        "name":"Plate",
        "tier":0,
        "count":2
      },{
        "name":"Circle",
        "tier":0,
        "count":2
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      },{
        "name":"Rubber",
        "tier":0,
        "count":4
      }],
    "Refiner":[
      {
        "name":"StackedPlate",
        "tier":0,
        "count":4
      },{
        "name":"Pump",
        "tier":0,
        "count":1
      },{
        "name":"Chip",
        "tier":0,
        "count":2
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      },{
        "name":"Circle",
        "tier":0,
        "count":1
      }
    ],
    "Assembly":[
      {
        "name":"StackedPlate",
        "tier":0,
        "count":6
      },{
        "name":"Roll",
        "tier":0,
        "count":1
      },{
        "name":"Chip",
        "tier":0,
        "count":1
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      }
    ],
    "Shaper":[
      {
        "name":"Plate",
        "tier":0,
        "count":4
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Bolt",
        "tier":0,
        "count":1
      },{
        "name":"InsulCable",
        "tier":0,
        "count":1
      },{
        "name":"Block",
        "tier":0,
        "count":1
      }
    ],
    "Block":[
      {
        "name":"StackedPlate",
        "tier":0,
        "count":8
      }
    ],
    "Cutter":[
      {
        "name":"Plate",
        "tier":0,
        "count":2
      },
      {
        "name":"StackedPlate",
        "tier":0,
        "count":3
      },{
        "name":"Motor",
        "tier":0,
        "count":3
      }
    ],
    "Boiler":[
      {
        "name":"StackedPlate",
        "tier":0,
        "count":2
      },{
        "name":"Bolt",
        "tier":0,
        "count":2
      },{
        "name":"Block",
        "tier":0,
        "count":4
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      },{
        "name":"Pump",
        "tier":0,
        "count":1
      },{
        "name":"Spin",
        "tier":0,
        "count":2
      }
    ]
  }
}
let parts = {
  "Spin":[{
    "name":"Cable",
    "tier":0,
    "count":1
  }],
  "Cable":[{
    "name":"Ingot",
    "tier":0,
    "count":0.5
  }],
  "Plate":[{
    "name": "Ingot",
    "tier": 0,
    "count": 1
  }],
  "Ingot":[{
    "name":"Dust",
    "tier":0,
    "count":1
  }],
  "AssCable":[{
    "name":"Cable",
    "tier":0,
    "count":1
  }],
  "RefPlate":[{
    "name":"Plate",
    "tier":0,
    "count":1
  }],
  "Bolt":[{
    "name":"Rod",
    "tier":0,
    "count":0.25
  }],
  "StackedPlate":[{
    "name":"Plate",
    "tier":0,
    "count":9
  }],
  "Rod":[{
    "name":"Ingot",
    "tier":0,
    "count":0.5
  }],
  "Circle":[{
    "name":"Rod",
    "tier":0,
    "count":1
  }],
  "BoiledBlock":[{
    "name":"Block",
    "tier":0,
    "count":1
  }],


}
let config = {
  "tiers":2,
  "machines":["Oven", "Assembly", "Refiner",
  "Crusher", "Cutter", "Presser", "Mixer",
  "Belt", "Shaper", "Boiler"],
  "parts":["Ingot", "AssCable", "Cable", "Spin", "RefPlate",
  "Bolt", "Plate", "StackedPlate", "Rod", "Circle",
  "BoiledBlock", "Block", "Pump", "Motor"]
}