let recipes = {
  "1": {
    "Oven":[
      {
        "name":"Plate",
        "tier":1,
        "count":4
      },
      {
        "name":"InsulCable",
        "tier":1,
        "count":2
      }],
    "Presser":[
      {
        "name":"Plate",
        "tier":1,
        "count":4
      },
      {
        "name":"Chip",
        "tier":1,
        "count":2
      },
      {
        "name":"Hammer",
        "tier":1,
        "count":2
      },
      {
        "name":"Wire",
        "tier":1,
        "count":1
      }],
    "Belt":[
      {
        "name":"Rubber",
        "tier":0,
        "count":3
      },{
        "name":"Motor",
        "tier":0,
        "count":3
      },{
        "name":"InsulCable",
        "tier":0,
        "count":3
      }],
    "Crusher":[
      {
        "name":"Chip",
        "tier":1,
        "count":1
      },{
        "name":"Motor",
        "tier":1,
        "count":1
      },{
        "name":"DensePlate",
        "tier":1,
        "count":7
      }
    ],
    "Mixer":[
      {
        "name":"Plate",
        "tier":0,
        "count":5
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Pump",
        "tier":0,
        "count":1
      },{
        "name":"Chip",
        "tier":1,
        "count":1
      }
    ],
    "Refiner":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":4
      },{
        "name":"Pump",
        "tier":0,
        "count":1
      },{
        "name":"Chip",
        "tier":1,
        "count":2
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      },{
        "name":"Ring",
        "tier":0,
        "count":1
      }
    ],
    "Assembly":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":6
      },{
        "name":"Pipe",
        "tier":0,
        "count":1
      },{
        "name":"Chip",
        "tier":1,
        "count":1
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      }
    ],
    "Shaper":[
      {
        "name":"Plate",
        "tier":0,
        "count":4
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Screw",
        "tier":0,
        "count":1
      },{
        "name":"InsulCable",
        "tier":0,
        "count":1
      },{
        "name":"Block",
        "tier":0,
        "count":1
      }
    ],
    "Cutter":[
      {
        "name":"Plate",
        "tier":0,
        "count":2
      },
      {
        "name":"DensePlate",
        "tier":0,
        "count":3
      },{
        "name":"Motor",
        "tier":0,
        "count":3
      }
    ],
    "Boiler":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":2
      },{
        "name":"Screw",
        "tier":0,
        "count":2
      },{
        "name":"Block",
        "tier":0,
        "count":4
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      },{
        "name":"Pump",
        "tier":0,
        "count":1
      },{
        "name":"Wire",
        "tier":0,
        "count":2
      }
    ],
    "Chip":[
      {
        "name":"CircuitWire",
        "tier":1,
        "count":2
      },
      {
        "name":"CircuitWire",
        "tier":2,
        "count":2
      },
      {
        "name":"CircuitPlate",
        "tier":1,
        "count":1
      },
      {
        "name":"CircuitPlate",
        "tier":2,
        "count":1
      }
    ],
    "InsulCable":[
      {
        "name":"Cable",
        "tier":1,
        "count":1
      },
      {
        "name":"Rubber",
        "tier":0,
        "count":1
      }],
    "Block":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":8
      }
    ],
    "Pump":[
      {
        "name":"Plate",
        "tier":0,
        "count":2
      },{
        "name":"Ring",
        "tier":0,
        "count":2
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      },{
        "name":"Rubber",
        "tier":0,
        "count":4
      }],
    "DensePlate":[
      {
        "name":"Plate",
        "tier":1,
        "count":9
      }
    ],
    "Motor":[
      {
        "name":"Plate",
        "tier":0,
        "count":4
      },
      {
        "name":"Rod",
        "tier":0,
        "count":2
      },{
        "name":"Wire",
        "tier":0,
        "count":1
      },{
        "name":"Screw",
        "tier":0,
        "count":1
      },{
        "name":"Rubber",
        "tier":0,
        "count":1
      }],
    "WhiteProducer":[
      {
        "name":"Plate",
        "tier":2,
        "count":2
      },
      {
        "name":"Screw",
        "tier":2,
        "count":2
      },]
  },
  "2": {
    "Oven":[
      {
        "name":"Plate",
        "tier":0,
        "count":6
      },
      {
        "name":"InsulCable",
        "tier":0,
        "count":2
      },
      {
        "name":"Oven",
        "tier":1,
        "count":1
      }
    ],
    "Presser":[
      {
        "name":"Plate",
        "tier":0,
        "count":5
      },
      {
        "name":"Chip",
        "tier":1,
        "count":2
      },
      {
        "name":"Presser",
        "tier":1,
        "count":1
      },
      {
        "name":"Wire",
        "tier":0,
        "count":1
      }],
    "Belt":[
      {
        "name":"Rubber",
        "tier":0,
        "count":4
      },{
        "name":"Motor",
        "tier":0,
        "count":3
      },{
        "name":"InsulCable",
        "tier":0,
        "count":4
      },
      {
        "name":"Belt",
        "tier":1,
        "count":1
      },],
    "Crusher":[
      {
        "name":"Chip",
        "tier":1,
        "count":2
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      },{
        "name":"DensePlate",
        "tier":0,
        "count":8
      },
      {
        "name":"Crusher",
        "tier":1,
        "count":1
      },
    ],
    "Mixer":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":4
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Pump",
        "tier":0,
        "count":1
      },{
        "name":"Chip",
        "tier":1,
        "count":1
      },
      {
        "name":"Mixer",
        "tier":1,
        "count":1
      },
    ],
    "Refiner":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":4
      },{
        "name":"Pump",
        "tier":0,
        "count":2
      },{
        "name":"Chip",
        "tier":1,
        "count":2
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      },{
        "name":"Ring",
        "tier":0,
        "count":2
      },
      {
        "name":"Refiner",
        "tier":1,
        "count":1
      },
    ],
    "Assembly":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":5
      },{
        "name":"Pipe",
        "tier":0,
        "count":1
      },{
        "name":"Chip",
        "tier":1,
        "count":1
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      },
      {
        "name":"Assembly",
        "tier":1,
        "count":1
      },
    ],
    "Shaper":[
      {
        "name":"Plate",
        "tier":0,
        "count":4
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Screw",
        "tier":0,
        "count":2
      },{
        "name":"InsulCable",
        "tier":0,
        "count":1
      },{
        "name":"Block",
        "tier":0,
        "count":2
      },
      {
        "name":"Shaper",
        "tier":1,
        "count":1
      },
    ],
    "Cutter":[
      {
        "name":"Plate",
        "tier":0,
        "count":2
      },
      {
        "name":"DensePlate",
        "tier":0,
        "count":3
      },{
        "name":"Motor",
        "tier":0,
        "count":4
      },
      {
        "name":"Cutter",
        "tier":1,
        "count":1
      },
    ],
    "Boiler":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":2
      },{
        "name":"Screw",
        "tier":0,
        "count":2
      },{
        "name":"Block",
        "tier":0,
        "count":7
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      },{
        "name":"Pump",
        "tier":0,
        "count":1
      },{
        "name":"Wire",
        "tier":0,
        "count":2
      },{
        "name":"Boiler",
        "tier":1,
        "count":1
      },
    ],
    "Chip":[
      {
        "name":"CircuitWire",
        "tier":3,
        "count":2
      },
      {
        "name":"CircuitWire",
        "tier":4,
        "count":4
      },
      {
        "name":"CircuitPlate",
        "tier":3,
        "count":4
      },
      {
        "name":"CircuitPlate",
        "tier":4,
        "count":2
      },
      {
        "name":"Chip",
        "tier":1,
        "count":4
      }
    ],
    "InsulCable":[
      {
        "name":"Cable",
        "tier":0,
        "count":1
      },
      {
        "name":"Rubber",
        "tier":0,
        "count":2
      }],
    "Block":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":8
      }
    ],
    "Pump":[
      {
        "name":"Plate",
        "tier":0,
        "count":2
      },{
        "name":"Ring",
        "tier":0,
        "count":2
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      },{
        "name":"Rubber",
        "tier":0,
        "count":4
      }],
    "DensePlate":[
      {
        "name":"Plate",
        "tier":0,
        "count":9
      }
    ],
    "Motor":[
      {
        "name":"Plate",
        "tier":0,
        "count":4
      },
      {
        "name":"Rod",
        "tier":0,
        "count":2
      },{
        "name":"Wire",
        "tier":0,
        "count":1
      },{
        "name":"Screw",
        "tier":0,
        "count":1
      },{
        "name":"Rubber",
        "tier":0,
        "count":1
      }],
    "WhiteProducer":[
      {
        "name":"CircuitPlate",
        "tier":3,
        "count":2
      },
      {
        "name":"Screw",
        "tier":3,
        "count":4
      },
      {
        "name":"Chip",
        "tier":1,
        "count":1
      },
      {
        "name":"WhiteProducer",
        "tier":1,
        "count":1
      }]
  },
  "3": {
    "Oven":[
      {
        "name":"Plate",
        "tier":0,
        "count":8
      },
      {
        "name":"InsulCable",
        "tier":0,
        "count":3
      },
      {
        "name":"Oven",
        "tier":2,
        "count":1
      }
    ],
    "Presser":[
      {
        "name":"Plate",
        "tier":0,
        "count":7
      },
      {
        "name":"Chip",
        "tier":1,
        "count":2
      },
      {
        "name":"Presser",
        "tier":2,
        "count":1
      },
      {
        "name":"Wire",
        "tier":0,
        "count":2
      }],
    "Belt":[
      {
        "name":"Rubber",
        "tier":0,
        "count":4
      },{
        "name":"Motor",
        "tier":0,
        "count":3
      },{
        "name":"InsulCable",
        "tier":0,
        "count":4
      },
      {
        "name":"Belt",
        "tier":2,
        "count":1
      },],
    "Crusher":[
      {
        "name":"Chip",
        "tier":1,
        "count":2
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      },{
        "name":"DensePlate",
        "tier":0,
        "count":8
      },
      {
        "name":"Crusher",
        "tier":2,
        "count":1
      },
    ],
    "Mixer":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":4
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Pump",
        "tier":0,
        "count":1
      },{
        "name":"Chip",
        "tier":1,
        "count":1
      },{
        "name":"Mixer",
        "tier":2,
        "count":1
      },
    ],
    "Refiner":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":4
      },{
        "name":"Pump",
        "tier":0,
        "count":2
      },{
        "name":"Chip",
        "tier":2,
        "count":2
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      },{
        "name":"Ring",
        "tier":0,
        "count":2
      },{
        "name":"Refiner",
        "tier":2,
        "count":1
      },
    ],
    "Assembly":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":8
      },{
        "name":"Pipe",
        "tier":0,
        "count":1
      },{
        "name":"Chip",
        "tier":1,
        "count":1
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      },{
        "name":"Assembly",
        "tier":2,
        "count":1
      },
    ],
    "Shaper":[
      {
        "name":"Plate",
        "tier":0,
        "count":4
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Screw",
        "tier":0,
        "count":2
      },{
        "name":"InsulCable",
        "tier":0,
        "count":1
      },{
        "name":"Block",
        "tier":0,
        "count":2
      },{
        "name":"Shaper",
        "tier":2,
        "count":1
      },
    ],
    "Cutter":[
      {
        "name":"Plate",
        "tier":0,
        "count":2
      },{
        "name":"DensePlate",
        "tier":0,
        "count":3
      },{
        "name":"Motor",
        "tier":0,
        "count":4
      },{
        "name":"Cutter",
        "tier":2,
        "count":1
      },
    ],
    "Boiler":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":2
      },{
        "name":"Screw",
        "tier":0,
        "count":2
      },{
        "name":"Block",
        "tier":0,
        "count":7
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      },{
        "name":"Pump",
        "tier":0,
        "count":1
      },{
        "name":"Wire",
        "tier":0,
        "count":2
      },{
        "name":"Boiler",
        "tier":2,
        "count":1
      },
    ],
    "Chip":[
      {
        "name":"CircuitWire",
        "tier":5,
        "count":2
      },{
        "name":"CircuitWire",
        "tier":6,
        "count":4
      },{
        "name":"CircuitPlate",
        "tier":5,
        "count":4
      },{
        "name":"CircuitPlate",
        "tier":6,
        "count":2
      },{
        "name":"Chip",
        "tier":2,
        "count":8
      }
    ],
    "InsulCable":[
      {
        "name":"Cable",
        "tier":0,
        "count":1
      },{
        "name":"Rubber",
        "tier":0,
        "count":2
      }],
    "Block":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":8
      }
    ],
    "Pump":[
      {
        "name":"Plate",
        "tier":0,
        "count":2
      },{
        "name":"Ring",
        "tier":0,
        "count":2
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      },{
        "name":"Rubber",
        "tier":0,
        "count":4
      }],
    "DensePlate":[
      {
        "name":"Plate",
        "tier":0,
        "count":9
      }
    ],
    "Motor":[
      {
        "name":"Plate",
        "tier":0,
        "count":4
      },
      {
        "name":"Rod",
        "tier":0,
        "count":2
      },{
        "name":"Wire",
        "tier":0,
        "count":1
      },{
        "name":"Screw",
        "tier":0,
        "count":1
      },{
        "name":"Rubber",
        "tier":0,
        "count":1
      }],
    "WhiteProducer":[
      {
        "name":"CircuitPlate",
        "tier":5,
        "count":2
      },
      {
        "name":"Screw",
        "tier":5,
        "count":4
      },
      {
        "name":"Chip",
        "tier":2,
        "count":1
      },
      {
        "name":"WhiteProducer",
        "tier":2,
        "count":1
      }]
  },
  "4": {
    "Oven":[
      {
        "name":"Plate",
        "tier":0,
        "count":8
      },
      {
        "name":"InsulCable",
        "tier":0,
        "count":3
      },
      {
        "name":"Oven",
        "tier":3,
        "count":1
      }
    ],
    "Presser":[
      {
        "name":"Plate",
        "tier":0,
        "count":7
      },{
        "name":"Chip",
        "tier":2,
        "count":2
      },{
        "name":"Presser",
        "tier":3,
        "count":1
      },{
        "name":"Wire",
        "tier":0,
        "count":2
      }],
    "Belt":[
      {
        "name":"Rubber",
        "tier":0,
        "count":4
      },{
        "name":"Motor",
        "tier":0,
        "count":3
      },{
        "name":"InsulCable",
        "tier":0,
        "count":4
      },{
        "name":"Belt",
        "tier":3,
        "count":1
      },{
        "name":"Chip",
        "tier":1,
        "count":4
      },],
    "Crusher":[
      {
        "name":"Chip",
        "tier":2,
        "count":2
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      },{
        "name":"DensePlate",
        "tier":0,
        "count":8
      },{
        "name":"Crusher",
        "tier":3,
        "count":1
      },
    ],
    "Mixer":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":5
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Pump",
        "tier":0,
        "count":2
      },{
        "name":"Chip",
        "tier":2,
        "count":2
      },{
        "name":"Mixer",
        "tier":3,
        "count":1
      },
    ],
    "Refiner":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":4
      },{
        "name":"Pump",
        "tier":0,
        "count":2
      },{
        "name":"Chip",
        "tier":2,
        "count":2
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      },{
        "name":"Ring",
        "tier":0,
        "count":2
      },{
        "name":"Refiner",
        "tier":3,
        "count":1
      },
    ],
    "Assembly":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":8
      },{
        "name":"Pipe",
        "tier":0,
        "count":1
      },{
        "name":"Chip",
        "tier":2,
        "count":1
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      },{
        "name":"Assembly",
        "tier":3,
        "count":1
      },
    ],
    "Shaper":[
      {
        "name":"Plate",
        "tier":0,
        "count":4
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Screw",
        "tier":0,
        "count":2
      },{
        "name":"InsulCable",
        "tier":0,
        "count":1
      },{
        "name":"Block",
        "tier":0,
        "count":2
      },{
        "name":"Shaper",
        "tier":3,
        "count":1
      },
    ],
    "Cutter":[
      {
        "name":"Plate",
        "tier":0,
        "count":2
      },{
        "name":"DensePlate",
        "tier":0,
        "count":3
      },{
        "name":"Motor",
        "tier":0,
        "count":4
      },{
        "name":"Cutter",
        "tier":3,
        "count":1
      },
    ],
    "Boiler":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":3
      },{
        "name":"Screw",
        "tier":0,
        "count":2
      },{
        "name":"Block",
        "tier":0,
        "count":8
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Pump",
        "tier":0,
        "count":1
      },{
        "name":"Wire",
        "tier":0,
        "count":3
      },{
        "name":"Boiler",
        "tier":3,
        "count":1
      },
    ],
    "Chip":[
      {
        "name":"CircuitWire",
        "tier":7,
        "count":2
      },{
        "name":"CircuitWire",
        "tier":8,
        "count":2
      },{
        "name":"CircuitPlate",
        "tier":7,
        "count":6
      },{
        "name":"CircuitPlate",
        "tier":8,
        "count":6
      },{
        "name":"Chip",
        "tier":3,
        "count":12
      }
    ],
    "InsulCable":[
      {
        "name":"Cable",
        "tier":0,
        "count":2
      },{
        "name":"Rubber",
        "tier":0,
        "count":4
      }],
    "Block":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":8
      }
    ],
    "Pump":[
      {
        "name":"Plate",
        "tier":0,
        "count":2
      },{
        "name":"Ring",
        "tier":0,
        "count":2
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      },{
        "name":"Rubber",
        "tier":0,
        "count":4
      }],
    "DensePlate":[
      {
        "name":"Plate",
        "tier":0,
        "count":9
      }
    ],
    "Motor":[
      {
        "name":"Plate",
        "tier":0,
        "count":4
      },
      {
        "name":"Rod",
        "tier":0,
        "count":2
      },{
        "name":"Wire",
        "tier":0,
        "count":1
      },{
        "name":"Screw",
        "tier":0,
        "count":1
      },{
        "name":"Rubber",
        "tier":0,
        "count":1
      }],
    "WhiteProducer":[
      {
        "name":"CircuitPlate",
        "tier":7,
        "count":2
      },
      {
        "name":"Screw",
        "tier":7,
        "count":4
      },
      {
        "name":"Chip",
        "tier":3,
        "count":1
      },
      {
        "name":"WhiteProducer",
        "tier":3,
        "count":1
      }]
  },
  "5": {
    "Oven":[
      {
        "name":"Plate",
        "tier":0,
        "count":8
      },{
        "name":"InsulCable",
        "tier":0,
        "count":3
      },{
        "name":"Oven",
        "tier":4,
        "count":1
      }
    ],
    "Presser":[
      {
        "name":"Plate",
        "tier":0,
        "count":7
      },{
        "name":"Chip",
        "tier":2,
        "count":2
      },{
        "name":"Presser",
        "tier":4,
        "count":1
      },{
        "name":"Wire",
        "tier":0,
        "count":2
      },{
        "name":"Block",
        "tier":0,
        "count":4
      }],
    "Belt":[
      {
        "name":"Rubber",
        "tier":0,
        "count":4
      },{
        "name":"Motor",
        "tier":0,
        "count":3
      },{
        "name":"InsulCable",
        "tier":0,
        "count":4
      },{
        "name":"Belt",
        "tier":4,
        "count":1
      },{
        "name":"Chip",
        "tier":2,
        "count":4
      },],
    "Crusher":[
      {
        "name":"Chip",
        "tier":2,
        "count":2
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      },{
        "name":"DensePlate",
        "tier":0,
        "count":8
      },{
        "name":"Crusher",
        "tier":4,
        "count":1
      },
    ],
    "Mixer":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":5
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Pump",
        "tier":0,
        "count":2
      },{
        "name":"Chip",
        "tier":2,
        "count":2
      },{
        "name":"Mixer",
        "tier":4,
        "count":1
      },
    ],
    "Refiner":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":4
      },{
        "name":"Pump",
        "tier":0,
        "count":3
      },{
        "name":"Chip",
        "tier":2,
        "count":2
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Ring",
        "tier":0,
        "count":3
      },{
        "name":"Refiner",
        "tier":4,
        "count":1
      },
    ],
    "Assembly":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":8
      },{
        "name":"Pipe",
        "tier":0,
        "count":1
      },{
        "name":"Chip",
        "tier":2,
        "count":1
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      },{
        "name":"Assembly",
        "tier":4,
        "count":1
      },
    ],
    "Shaper":[
      {
        "name":"Plate",
        "tier":0,
        "count":4
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Screw",
        "tier":0,
        "count":2
      },{
        "name":"InsulCable",
        "tier":0,
        "count":1
      },{
        "name":"Block",
        "tier":0,
        "count":2
      },{
        "name":"Shaper",
        "tier":4,
        "count":1
      },
    ],
    "Cutter":[
      {
        "name":"Plate",
        "tier":0,
        "count":2
      },{
        "name":"DensePlate",
        "tier":0,
        "count":3
      },{
        "name":"Motor",
        "tier":0,
        "count":4
      },{
        "name":"Cutter",
        "tier":4,
        "count":1
      },
    ],
    "Boiler":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":3
      },{
        "name":"Screw",
        "tier":0,
        "count":2
      },{
        "name":"Block",
        "tier":0,
        "count":8
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Pump",
        "tier":0,
        "count":1
      },{
        "name":"Wire",
        "tier":0,
        "count":3
      },{
        "name":"Boiler",
        "tier":4,
        "count":1
      },
    ],
    "Chip":[
      {
        "name":"CircuitWire",
        "tier":9,
        "count":2
      },{
        "name":"CircuitWire",
        "tier":10,
        "count":2
      },{
        "name":"CircuitPlate",
        "tier":9,
        "count":8
      },{
        "name":"CircuitPlate",
        "tier":10,
        "count":8
      },{
        "name":"Chip",
        "tier":4,
        "count":12
      }
    ],
    "InsulCable":[
      {
        "name":"Cable",
        "tier":0,
        "count":3
      },{
        "name":"Rubber",
        "tier":0,
        "count":6
      }],
    "Block":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":8
      }
    ],
    "Pump":[
      {
        "name":"Plate",
        "tier":0,
        "count":2
      },{
        "name":"Ring",
        "tier":0,
        "count":2
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      },{
        "name":"Rubber",
        "tier":0,
        "count":4
      }],
    "DensePlate":[
      {
        "name":"Plate",
        "tier":0,
        "count":9
      }
    ],
    "Motor":[
      {
        "name":"Plate",
        "tier":0,
        "count":4
      },
      {
        "name":"Rod",
        "tier":0,
        "count":2
      },{
        "name":"Wire",
        "tier":0,
        "count":1
      },{
        "name":"Screw",
        "tier":0,
        "count":1
      },{
        "name":"Rubber",
        "tier":0,
        "count":1
      }],
    "WhiteProducer":[
      {
        "name":"CircuitPlate",
        "tier":9,
        "count":6
      },
      {
        "name":"Screw",
        "tier":9,
        "count":4
      },
      {
        "name":"Chip",
        "tier":4,
        "count":4
      },
      {
        "name":"WhiteProducer",
        "tier":4,
        "count":1
      }]
  },
  "6": {
    "Oven":[
      {
        "name":"Plate",
        "tier":0,
        "count":8
      },{
        "name":"InsulCable",
        "tier":0,
        "count":4
      },{
        "name":"Oven",
        "tier":5,
        "count":1
      },{
        "name":"Block",
        "tier":0,
        "count":2
      }
    ],
    "Presser":[
      {
        "name":"Plate",
        "tier":0,
        "count":9
      },{
        "name":"Chip",
        "tier":2,
        "count":2
      },{
        "name":"Presser",
        "tier":5,
        "count":1
      },{
        "name":"Wire",
        "tier":0,
        "count":3
      },{
        "name":"Block",
        "tier":0,
        "count":5
      }],
    "Belt":[
      {
        "name":"Rubber",
        "tier":0,
        "count":4
      },{
        "name":"Motor",
        "tier":0,
        "count":3
      },{
        "name":"InsulCable",
        "tier":0,
        "count":4
      },{
        "name":"Belt",
        "tier":5,
        "count":1
      },{
        "name":"Chip",
        "tier":2,
        "count":4
      },],
    "Crusher":[
      {
        "name":"Chip",
        "tier":2,
        "count":2
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      },{
        "name":"DensePlate",
        "tier":0,
        "count":8
      },{
        "name":"Crusher",
        "tier":5,
        "count":1
      },
    ],
    "Mixer":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":6
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Pump",
        "tier":0,
        "count":3
      },{
        "name":"Chip",
        "tier":2,
        "count":3
      },{
        "name":"Mixer",
        "tier":5,
        "count":1
      },
    ],
    "Refiner":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":4
      },{
        "name":"Pump",
        "tier":0,
        "count":3
      },{
        "name":"Chip",
        "tier":2,
        "count":2
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Ring",
        "tier":0,
        "count":3
      },{
        "name":"Refiner",
        "tier":5,
        "count":1
      },
    ],
    "Assembly":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":10
      },{
        "name":"Pipe",
        "tier":0,
        "count":2
      },{
        "name":"Chip",
        "tier":2,
        "count":1
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      },{
        "name":"Assembly",
        "tier":5,
        "count":1
      },
    ],
    "Shaper":[
      {
        "name":"Plate",
        "tier":0,
        "count":4
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Screw",
        "tier":0,
        "count":3
      },{
        "name":"InsulCable",
        "tier":0,
        "count":2
      },{
        "name":"Block",
        "tier":0,
        "count":3
      },{
        "name":"Shaper",
        "tier":5,
        "count":1
      },
    ],
    "Cutter":[
      {
        "name":"Plate",
        "tier":0,
        "count":2
      },{
        "name":"DensePlate",
        "tier":0,
        "count":4
      },{
        "name":"Motor",
        "tier":0,
        "count":5
      },{
        "name":"Cutter",
        "tier":5,
        "count":1
      },
    ],
    "Boiler":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":3
      },{
        "name":"Screw",
        "tier":0,
        "count":2
      },{
        "name":"Block",
        "tier":0,
        "count":8
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Pump",
        "tier":0,
        "count":1
      },{
        "name":"Wire",
        "tier":0,
        "count":3
      },{
        "name":"Boiler",
        "tier":5,
        "count":1
      },
    ],
    "InsulCable":[
      {
        "name":"Cable",
        "tier":0,
        "count":4
      },{
        "name":"Rubber",
        "tier":0,
        "count":8
      }],
    "Block":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":8
      }
    ],
    "Pump":[
      {
        "name":"Plate",
        "tier":0,
        "count":2
      },{
        "name":"Ring",
        "tier":0,
        "count":2
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      },{
        "name":"Rubber",
        "tier":0,
        "count":4
      }],
    "DensePlate":[
      {
        "name":"Plate",
        "tier":0,
        "count":9
      }
    ],
    "Motor":[
      {
        "name":"Plate",
        "tier":0,
        "count":4
      },
      {
        "name":"Rod",
        "tier":0,
        "count":2
      },{
        "name":"Wire",
        "tier":0,
        "count":1
      },{
        "name":"Screw",
        "tier":0,
        "count":1
      },{
        "name":"Rubber",
        "tier":0,
        "count":1
      }],
  },
  "7": {
    "Oven":[
      {
        "name":"Plate",
        "tier":0,
        "count":8
      },{
        "name":"InsulCable",
        "tier":0,
        "count":4
      },{
        "name":"Oven",
        "tier":6,
        "count":1
      },{
        "name":"Block",
        "tier":0,
        "count":2
      }
    ],
    "Presser":[
      {
        "name":"Plate",
        "tier":0,
        "count":9
      },{
        "name":"Chip",
        "tier":3,
        "count":2
      },{
        "name":"Presser",
        "tier":6,
        "count":1
      },{
        "name":"Wire",
        "tier":0,
        "count":3
      },{
        "name":"Block",
        "tier":0,
        "count":5
      }],
    "Belt":[
      {
        "name":"Rubber",
        "tier":0,
        "count":5
      },{
        "name":"Motor",
        "tier":0,
        "count":4
      },{
        "name":"InsulCable",
        "tier":0,
        "count":5
      },{
        "name":"Belt",
        "tier":6,
        "count":1
      },{
        "name":"Chip",
        "tier":3,
        "count":5
      },],
    "Crusher":[
      {
        "name":"Chip",
        "tier":2,
        "count":2
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      },{
        "name":"DensePlate",
        "tier":0,
        "count":8
      },{
        "name":"Crusher",
        "tier":6,
        "count":1
      },
    ],
    "Mixer":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":6
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Pump",
        "tier":0,
        "count":3
      },{
        "name":"Chip",
        "tier":2,
        "count":3
      },{
        "name":"Mixer",
        "tier":6,
        "count":1
      },
    ],
    "Refiner":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":4
      },{
        "name":"Pump",
        "tier":0,
        "count":3
      },{
        "name":"Chip",
        "tier":3,
        "count":2
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Ring",
        "tier":0,
        "count":3
      },{
        "name":"Refiner",
        "tier":6,
        "count":1
      },{
        "name":"Block",
        "tier":0,
        "count":5
      },
    ],
    "Assembly":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":10
      },{
        "name":"Pipe",
        "tier":0,
        "count":2
      },{
        "name":"Chip",
        "tier":3,
        "count":1
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      },{
        "name":"Assembly",
        "tier":6,
        "count":1
      },
    ],
    "Shaper":[
      {
        "name":"Plate",
        "tier":0,
        "count":4
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Screw",
        "tier":0,
        "count":3
      },{
        "name":"InsulCable",
        "tier":0,
        "count":2
      },{
        "name":"Block",
        "tier":0,
        "count":3
      },{
        "name":"Shaper",
        "tier":6,
        "count":1
      },
    ],
    "Cutter":[
      {
        "name":"Plate",
        "tier":0,
        "count":2
      },{
        "name":"DensePlate",
        "tier":0,
        "count":4
      },{
        "name":"Motor",
        "tier":0,
        "count":5
      },{
        "name":"Cutter",
        "tier":6,
        "count":1
      },
    ],
    "Boiler":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":3
      },{
        "name":"Screw",
        "tier":0,
        "count":2
      },{
        "name":"Block",
        "tier":0,
        "count":8
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Pump",
        "tier":0,
        "count":1
      },{
        "name":"Wire",
        "tier":0,
        "count":3
      },{
        "name":"Boiler",
        "tier":6,
        "count":1
      },
    ],
    "InsulCable":[
      {
        "name":"Cable",
        "tier":0,
        "count":5
      },{
        "name":"Rubber",
        "tier":0,
        "count":10
      }],
    "Block":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":12
      }
    ],
    "Pump":[
      {
        "name":"Plate",
        "tier":0,
        "count":2
      },{
        "name":"Ring",
        "tier":0,
        "count":2
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      },{
        "name":"Rubber",
        "tier":0,
        "count":4
      }],
    "DensePlate":[
      {
        "name":"Plate",
        "tier":0,
        "count":9
      }
    ],
    "Motor":[
      {
        "name":"Plate",
        "tier":0,
        "count":4
      },
      {
        "name":"Rod",
        "tier":0,
        "count":2
      },{
        "name":"Wire",
        "tier":0,
        "count":1
      },{
        "name":"Screw",
        "tier":0,
        "count":1
      },{
        "name":"Rubber",
        "tier":0,
        "count":1
      }],
  },
  "8": {
    "Oven":[
      {
        "name":"Plate",
        "tier":0,
        "count":8
      },{
        "name":"InsulCable",
        "tier":0,
        "count":4
      },{
        "name":"Oven",
        "tier":7,
        "count":1
      },{
        "name":"Block",
        "tier":0,
        "count":2
      }
    ],
    "Presser":[
      {
        "name":"Plate",
        "tier":0,
        "count":9
      },{
        "name":"Chip",
        "tier":3,
        "count":2
      },{
        "name":"Presser",
        "tier":7,
        "count":1
      },{
        "name":"Wire",
        "tier":0,
        "count":3
      },{
        "name":"Block",
        "tier":0,
        "count":5
      }],
    "Belt":[
      {
        "name":"Rubber",
        "tier":0,
        "count":5
      },{
        "name":"Motor",
        "tier":0,
        "count":4
      },{
        "name":"InsulCable",
        "tier":0,
        "count":5
      },{
        "name":"Belt",
        "tier":7,
        "count":1
      },{
        "name":"Chip",
        "tier":3,
        "count":5
      },],
    "Crusher":[
      {
        "name":"Chip",
        "tier":2,
        "count":3
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"DensePlate",
        "tier":0,
        "count":9
      },{
        "name":"Crusher",
        "tier":7,
        "count":1
      },
    ],
    "Mixer":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":6
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Pump",
        "tier":0,
        "count":3
      },{
        "name":"Chip",
        "tier":3,
        "count":3
      },{
        "name":"Mixer",
        "tier":7,
        "count":1
      },
    ],
    "Refiner":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":4
      },{
        "name":"Pump",
        "tier":0,
        "count":3
      },{
        "name":"Chip",
        "tier":4,
        "count":2
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Ring",
        "tier":0,
        "count":3
      },{
        "name":"Refiner",
        "tier":7,
        "count":1
      },{
        "name":"Block",
        "tier":0,
        "count":5
      },
    ],
    "Assembly":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":10
      },{
        "name":"Pipe",
        "tier":0,
        "count":2
      },{
        "name":"Chip",
        "tier":3,
        "count":1
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      },{
        "name":"Assembly",
        "tier":7,
        "count":1
      },
    ],
    "Shaper":[
      {
        "name":"Plate",
        "tier":0,
        "count":4
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Screw",
        "tier":0,
        "count":3
      },{
        "name":"InsulCable",
        "tier":0,
        "count":2
      },{
        "name":"Block",
        "tier":0,
        "count":3
      },{
        "name":"Shaper",
        "tier":7,
        "count":1
      },
    ],
    "Cutter":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":2
      },{
        "name":"Block",
        "tier":0,
        "count":4
      },{
        "name":"Motor",
        "tier":0,
        "count":5
      },{
        "name":"Cutter",
        "tier":7,
        "count":1
      },
    ],
    "Boiler":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":3
      },{
        "name":"Screw",
        "tier":0,
        "count":2
      },{
        "name":"Block",
        "tier":0,
        "count":8
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Pump",
        "tier":0,
        "count":1
      },{
        "name":"Wire",
        "tier":0,
        "count":3
      },{
        "name":"Boiler",
        "tier":7,
        "count":1
      },
    ],
    "InsulCable":[
      {
        "name":"Cable",
        "tier":0,
        "count":10
      },{
        "name":"Rubber",
        "tier":0,
        "count":10
      }],
    "Block":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":12
      }
    ],
    "Pump":[
      {
        "name":"Plate",
        "tier":0,
        "count":2
      },{
        "name":"Ring",
        "tier":0,
        "count":2
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      },{
        "name":"Rubber",
        "tier":0,
        "count":4
      }],
    "DensePlate":[
      {
        "name":"Plate",
        "tier":0,
        "count":9
      }
    ],
    "Motor":[
      {
        "name":"Plate",
        "tier":0,
        "count":4
      },
      {
        "name":"Rod",
        "tier":0,
        "count":2
      },{
        "name":"Wire",
        "tier":0,
        "count":1
      },{
        "name":"Screw",
        "tier":0,
        "count":1
      },{
        "name":"Rubber",
        "tier":0,
        "count":1
      }],
  },
  "9": {
    "Oven":[
      {
        "name":"Plate",
        "tier":0,
        "count":8
      },{
        "name":"InsulCable",
        "tier":0,
        "count":4
      },{
        "name":"Oven",
        "tier":8,
        "count":1
      },{
        "name":"Block",
        "tier":0,
        "count":2
      }
    ],
    "Presser":[
      {
        "name":"Plate",
        "tier":0,
        "count":9
      },{
        "name":"Chip",
        "tier":4,
        "count":2
      },{
        "name":"Presser",
        "tier":8,
        "count":1
      },{
        "name":"Wire",
        "tier":0,
        "count":3
      },{
        "name":"Block",
        "tier":0,
        "count":5
      }],
    "Belt":[
      {
        "name":"Rubber",
        "tier":0,
        "count":5
      },{
        "name":"Motor",
        "tier":0,
        "count":4
      },{
        "name":"InsulCable",
        "tier":0,
        "count":5
      },{
        "name":"Belt",
        "tier":8,
        "count":1
      },{
        "name":"Chip",
        "tier":4,
        "count":5
      },],
    "Crusher":[
      {
        "name":"Chip",
        "tier":4,
        "count":3
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"DensePlate",
        "tier":0,
        "count":9
      },{
        "name":"Crusher",
        "tier":8,
        "count":1
      },
    ],
    "Mixer":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":6
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Pump",
        "tier":0,
        "count":3
      },{
        "name":"Chip",
        "tier":4,
        "count":3
      },{
        "name":"Mixer",
        "tier":8,
        "count":1
      },
    ],
    "Refiner":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":4
      },{
        "name":"Pump",
        "tier":0,
        "count":3
      },{
        "name":"Chip",
        "tier":4,
        "count":2
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Ring",
        "tier":0,
        "count":3
      },{
        "name":"Refiner",
        "tier":8,
        "count":1
      },{
        "name":"Block",
        "tier":0,
        "count":5
      },
    ],
    "Assembly":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":12
      },{
        "name":"Pipe",
        "tier":0,
        "count":2
      },{
        "name":"Chip",
        "tier":4,
        "count":1
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Assembly",
        "tier":8,
        "count":1
      },
    ],
    "Shaper":[
      {
        "name":"Plate",
        "tier":0,
        "count":4
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Screw",
        "tier":0,
        "count":3
      },{
        "name":"InsulCable",
        "tier":0,
        "count":2
      },{
        "name":"Block",
        "tier":0,
        "count":3
      },{
        "name":"Shaper",
        "tier":8,
        "count":1
      },
    ],
    "Cutter":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":2
      },{
        "name":"Block",
        "tier":0,
        "count":4
      },{
        "name":"Motor",
        "tier":0,
        "count":5
      },{
        "name":"Cutter",
        "tier":8,
        "count":1
      },
    ],
    "Boiler":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":4
      },{
        "name":"Screw",
        "tier":0,
        "count":2
      },{
        "name":"Block",
        "tier":0,
        "count":9
      },{
        "name":"Motor",
        "tier":0,
        "count":3
      },{
        "name":"Pump",
        "tier":0,
        "count":1
      },{
        "name":"Wire",
        "tier":0,
        "count":4
      },{
        "name":"Boiler",
        "tier":8,
        "count":1
      },
    ],
    "InsulCable":[
      {
        "name":"Cable",
        "tier":0,
        "count":12
      },{
        "name":"Rubber",
        "tier":0,
        "count":12
      }],
    "Block":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":12
      }
    ],
    "Pump":[
      {
        "name":"Plate",
        "tier":0,
        "count":2
      },{
        "name":"Ring",
        "tier":0,
        "count":2
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      },{
        "name":"Rubber",
        "tier":0,
        "count":4
      }],
    "DensePlate":[
      {
        "name":"Plate",
        "tier":0,
        "count":9
      }
    ],
    "Motor":[
      {
        "name":"Plate",
        "tier":0,
        "count":4
      },
      {
        "name":"Rod",
        "tier":0,
        "count":2
      },{
        "name":"Wire",
        "tier":0,
        "count":1
      },{
        "name":"Screw",
        "tier":0,
        "count":1
      },{
        "name":"Rubber",
        "tier":0,
        "count":1
      }],
  },
  "10": {
    "Oven":[
      {
        "name":"Plate",
        "tier":0,
        "count":8
      },{
        "name":"InsulCable",
        "tier":0,
        "count":4
      },{
        "name":"Oven",
        "tier":9,
        "count":1
      },{
        "name":"Block",
        "tier":0,
        "count":2
      }
    ],
    "Presser":[
      {
        "name":"Plate",
        "tier":0,
        "count":9
      },{
        "name":"Chip",
        "tier":4,
        "count":2
      },{
        "name":"Presser",
        "tier":9,
        "count":1
      },{
        "name":"Wire",
        "tier":0,
        "count":3
      },{
        "name":"Block",
        "tier":0,
        "count":5
      }],
    "Belt":[
      {
        "name":"Rubber",
        "tier":0,
        "count":5
      },{
        "name":"Motor",
        "tier":0,
        "count":4
      },{
        "name":"InsulCable",
        "tier":0,
        "count":5
      },{
        "name":"Belt",
        "tier":9,
        "count":1
      },{
        "name":"Chip",
        "tier":4,
        "count":5
      },],
    "Crusher":[
      {
        "name":"Chip",
        "tier":4,
        "count":3
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"DensePlate",
        "tier":0,
        "count":9
      },{
        "name":"Crusher",
        "tier":9,
        "count":1
      },
    ],
    "Mixer":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":6
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Pump",
        "tier":0,
        "count":3
      },{
        "name":"Chip",
        "tier":4,
        "count":3
      },{
        "name":"Mixer",
        "tier":9,
        "count":1
      },
    ],
    "Refiner":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":4
      },{
        "name":"Pump",
        "tier":0,
        "count":5
      },{
        "name":"Chip",
        "tier":5,
        "count":2
      },{
        "name":"Motor",
        "tier":0,
        "count":4
      },{
        "name":"Ring",
        "tier":0,
        "count":5
      },{
        "name":"Refiner",
        "tier":9,
        "count":1
      },{
        "name":"Block",
        "tier":0,
        "count":7
      },
    ],
    "Assembly":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":12
      },{
        "name":"Pipe",
        "tier":0,
        "count":2
      },{
        "name":"Chip",
        "tier":4,
        "count":2
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Assembly",
        "tier":9,
        "count":1
      },
    ],
    "Shaper":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":4
      },{
        "name":"Motor",
        "tier":0,
        "count":2
      },{
        "name":"Screw",
        "tier":0,
        "count":3
      },{
        "name":"InsulCable",
        "tier":0,
        "count":4
      },{
        "name":"BoiledBlock",
        "tier":0,
        "count":5
      },{
        "name":"Shaper",
        "tier":9,
        "count":1
      },
    ],
    "Cutter":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":2
      },{
        "name":"Block",
        "tier":0,
        "count":6
      },{
        "name":"Motor",
        "tier":0,
        "count":7
      },{
        "name":"Cutter",
        "tier":9,
        "count":1
      },
    ],
    "Boiler":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":5
      },{
        "name":"Screw",
        "tier":0,
        "count":2
      },{
        "name":"Block",
        "tier":0,
        "count":10
      },{
        "name":"Motor",
        "tier":0,
        "count":4
      },{
        "name":"Pump",
        "tier":0,
        "count":1
      },{
        "name":"Wire",
        "tier":0,
        "count":5
      },{
        "name":"Boiler",
        "tier":9,
        "count":1
      },
    ],
    "InsulCable":[
      {
        "name":"Cable",
        "tier":0,
        "count":16
      },{
        "name":"Rubber",
        "tier":0,
        "count":16
      }],
    "Block":[
      {
        "name":"DensePlate",
        "tier":0,
        "count":12
      }
    ],
    "Pump":[
      {
        "name":"Plate",
        "tier":0,
        "count":2
      },{
        "name":"Ring",
        "tier":0,
        "count":2
      },{
        "name":"Motor",
        "tier":0,
        "count":1
      },{
        "name":"Rubber",
        "tier":0,
        "count":4
      }],
    "DensePlate":[
      {
        "name":"Plate",
        "tier":0,
        "count":9
      }
    ],
    "Motor":[
      {
        "name":"Plate",
        "tier":0,
        "count":4
      },
      {
        "name":"Rod",
        "tier":0,
        "count":2
      },{
        "name":"Wire",
        "tier":0,
        "count":1
      },{
        "name":"Screw",
        "tier":0,
        "count":1
      },{
        "name":"Rubber",
        "tier":0,
        "count":1
      }],
    "BoiledBlock":[
      {
        "name":"Block",
        "tier":0,
        "count":1
      }
    ],
    "ExoticProducer":[
      {
        "name":"Oven",
        "tier":10,
        "count":1
      },
      {
        "name":"Presser",
        "tier":10,
        "count":1
      },
      {
        "name":"Belt",
        "tier":10,
        "count":1
      },
      {
        "name":"Crusher",
        "tier":10,
        "count":1
      },
      {
        "name":"Mixer",
        "tier":10,
        "count":1
      },
      {
        "name":"Refiner",
        "tier":10,
        "count":1
      },
      {
        "name":"Assembly",
        "tier":10,
        "count":1
      },
      {
        "name":"Shaper",
        "tier":10,
        "count":1
      },
      {
        "name":"Cutter",
        "tier":10,
        "count":1
      },
      {
        "name":"Boiler",
        "tier":10,
        "count":1
      },
      {
        "name":"BoiledBlock",
        "tier":10,
        "count":10
      },
      {
        "name":"InsulCable",
        "tier":10,
        "count":2
      },
      {
        "name":"Chip",
        "tier":5,
        "count":10
      },
    ],
    "GemProducer":[
      {
        "name":"Block",
        "tier":1,
        "count":1
      },{
        "name":"Block",
        "tier":2,
        "count":1
      },{
        "name":"Block",
        "tier":3,
        "count":1
      },{
        "name":"Block",
        "tier":4,
        "count":1
      },{
        "name":"Block",
        "tier":5,
        "count":1
      },{
        "name":"Block",
        "tier":6,
        "count":1
      },{
        "name":"Block",
        "tier":7,
        "count":1
      },{
        "name":"Block",
        "tier":8,
        "count":1
      },{
        "name":"Block",
        "tier":9,
        "count":1
      },{
        "name":"Block",
        "tier":10,
        "count":1
      },{
        "name":"InsulCable",
        "tier":10,
        "count":2
      },{
        "name":"Chip",
        "tier":4,
        "count":10
      },{
        "name":"Chip",
        "tier":5,
        "count":10
      },
    ]
  }
}
let parts = {
  "Wire":[{
    "name":"Cable",
    "tier":0,
    "count":1
  }],
  "Cable":[{
    "name":"Ingot",
    "tier":0,
    "count":0.5
  }],
  "Plate":[{
    "name": "Ingot",
    "tier": 0,
    "count": 1
  }],
  "Ingot":[{
    "name":"Dust",
    "tier":0,
    "count":1
  }],
  "CircuitWire":[{
    "name":"Cable",
    "tier":0,
    "count":1
  }],
  "CircuitPlate":[{
    "name":"Plate",
    "tier":0,
    "count":1
  }],
  "Screw":[{
    "name":"Rod",
    "tier":0,
    "count":0.25
  }],
  "DensePlate":[{
    "name":"Plate",
    "tier":0,
    "count":9
  }],
  "Rod":[{
    "name":"Ingot",
    "tier":0,
    "count":0.5
  }],
  "Ring":[{
    "name":"Rod",
    "tier":0,
    "count":1
  }],
  "BoiledBlock":[{
    "name":"Block",
    "tier":0,
    "count":1
  }]
}
let config = {
  "tiers":10,
  "machines":["Oven", "Assembly", "Refiner",
  "Crusher", "Cutter", "Presser", "Mixer",
  "Belt", "Shaper", "Boiler", "ExoticProducer","GemProducer",
  "WhiteProducer"],
  "parts":["Ingot", "CircuitWire", "Cable", "Wire", "CircuitPlate",
  "Screw", "Plate", "DensePlate", "Rod", "Ring",
  "BoiledBlock", "Block", "Pump", "Motor"]
}
